### ISSUE TITLE
Upgrade Kubernetes master and workers to 1.11

### ISSUE THREAD

**Issue by The-smooth-operator** [mozilla-iam/eks-deployment#135]
There's a new version of Kubernetes available in EKS: 1.11. 
We want to update in order to don't fall behind, use newer features and practice the upgrade process before the cluster is fully into production.
We will be doing it first in the old-prod cluster, and after some days, in the new prod cluster.

**Comment by danielhartnell** [comment]
I made some notes about the upgrades here:

https://github.com/mozilla-iam/eks-deployment/blob/development/docs/eks-cluster-management.md#toc-upgrades

The work is done and the master / workers have been updated to 1.11.

**Comment by danielhartnell** [comment]
Making a note that this was not done in the old cluster because it did not have the Terraform support we needed to update the workers. It was done on the new cluster.
