### ISSUE TITLE
Cannot add new identity

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/eks-deployment#65]
**STR:** 
1. Login to mozillians staging 
2. Navigate to Settings page
3. Click "Add Identity" button in the "Profile Identities" section

**Expected results:**
Login window is shown, with all login options

**Actual results:**
Error page is displayed

<img width="971" alt="screen shot 2018-10-02 at 23 35 21" src="https://user-images.githubusercontent.com/5293100/46375365-eb04f000-c69b-11e8-985d-0c668735aea8.png">

**Comment by danielhartnell** [comment]
Hey @viorelaioia,

I updated the list of allowed callback URLs which should resolve this issue. I no longer see this error after following your steps to reproduce. Please let me know if you continue to see problems.

**Comment by viorelaioia** [comment]
This is fixed :+1:
