### ISSUE TITLE
Search is working only if the entire name of a contact or group is entered 

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/eks-deployment#66]
[Preconditions]:
vioia@mozilla.com member is created

[STR]:
1.Login to mozillians staging
2.Go to the search box and search for "v"

[Expected result]:
All groups and contacts which are starting with "v" are displayed as search results

[Actual result]:
Sorry we cannot find a group or profile related to "v" message is returned

[Note]:
The issue is not reproducible on mozillians prod
It works fine if searching for the entire name

**Comment by danielhartnell** [comment]
The `mozillians.users.tasks.index_all_profiles` task is currently failing. It appears to be prefixing the index name with 'current_' which is resulting in a 404 when communicating with Elasticsearch.

**Comment by danielhartnell** [comment]
Hey @akatsoulas,

Can you tell me what version of Elasticsearch you are using for Mozillians today?

When I setup Elasticsearch, I referred to some of the existing [partinfra Terraform](https://github.com/mozilla/partinfra-terraform/search?q=elasticsearch&unscoped_q=elasticsearch) which had Elasticsearch version 2.3 specified. This was missing a lot of functionality, including access to `_reindex`. I upgraded to 5.6 but now I'm seeing the following issue when trying to update the search index. Before I dig into this more, I figured I should make sure I'm using the same Elasticsearch version.

```
RequestError(400, u'parsing_exception', {u'status': 400, u'error': {u'root_cause': [{u'reason': u'Failed to build [alias_action] after last required field arrived', u'type': u'parsing_exception'}], u'caused_by': {u'type': u'parsing_exception', u'reason': u'Failed to build [alias_action] after last required field arrived', u'caused_by': {u'reason': u'Too many operations declared in on opeation entry', u'type': u'illegal_argument_exception'}}, u'reason': u'[aliases] failed to parse field [actions]', u'line': 1, u'type': u'parsing_exception', u'col': 206}}) 
```

This refers to line 340 in `mozillians/users/tasks.py`:

https://github.com/mozilla/mozillians/blob/master/mozillians/users/tasks.py#L340

**Comment by danielhartnell** [comment]
I spoke with nemo and we are using version 2.3 today rather than 5.x. I have restored 2.3 and I'll be working through some documentation he sent me to reindex.

**Comment by danielhartnell** [comment]
nemo and I discussed this further and we have agreed to close this out for now. The current functionality is sufficient for what we want to accomplish in the short term.
