### ISSUE TITLE
[Intermittent issue]: The results could not be loaded for Country field

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/eks-deployment#68]
[STR]:
1.Login to mozillians staging
2.Go to Country field and start typing (e.g. Ro)

[Expected result]:
The search results should be displayed

[Actual result]:
"The results could not be loaded" message is displayed

[Note]:
The issue is intermittent
The profile picture for this account is automatically updated from the account created in prod and couldn't be changed

![2018-10-03_15h06_37](https://user-images.githubusercontent.com/41474886/46414350-98731480-c72b-11e8-926e-dda0993617e7.png)

**Comment by danielhartnell** [comment]
I expect #66 to resolve this once I'm able to reindex in Elasticsearch.

**Comment by danielhartnell** [comment]
Hi @rleitan,

I was able to fix this with an Elasticsearch re-index. Thank you.

**Comment by rleitan** [comment]
I verified the issue,  using the same account and it seems to be fixed.
Thank you
